[project]
authors = ["Amy Van Scoyoc <avanscoyoc@berkeley.edu>"]
channels = ["conda-forge"]
description = "A comparison of machine learning model performance on non-avian audio"
name = "non-avian-ml-toy"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
libgl = "*"
glib = "*"
pixi-kernel = ">=0.6.2,<0.7"
pip = ">=25.0.1,<26"
fastapi = ">=0.115.12,<0.116"
uvicorn = ">=0.34.3,<0.35"
click = ">=8.2.1,<9"

[pypi-dependencies] 
tensorflow = "==2.14.0"
tensorflow_hub = "*"
opensoundscape = ">=0.11.0"
torch = "*"
numpy = "*"
pandas = "*"
tqdm = "*"
timm = "*"
torchaudio = "*"
executing = "*"
scikit-learn = ">=1.6.1, <2"
seaborn = "*"
onnx = "*"
onnxruntime = "*"
ai-edge-litert = "*"
google-cloud-storage = "*"
google-cloud-run = "*"
