[project]
authors = ["Amy Van Scoyoc <avanscoyoc@berkeley.edu>"]
channels = ["conda-forge"]
description = "A comparison of machine learning model performance on non-avian audio"
name = "bird_new"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10"
libgl = "*"
glib = "*"
pixi-kernel = ">=0.6.2,<0.7"
pip = ">=25.0.1,<26"

[pypi-dependencies] 
tensorflow_hub = "*"
opensoundscape = ">=0.11.0"
torch = "*"
numpy = "*"
pandas = "*"
tqdm = "*"
timm = "*"
torchaudio = "*"
tensorflow = "*"
executing = "*"
scikit-learn = ">=1.6.1, <2"
