[project]
authors = ["GondekNP <npg@berkeley.edu>"]
channels = ["conda-forge"]
description = "A demo devcontainer pixi setup"
name = "devcontainer_template"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10"
tensorflow = "2.14.0"

[pypi-dependencies] 
opensoundscape = ">=0.11.0"