[project]
authors = ["Amy Van Scoyoc <avanscoyoc@berkeley.edu>"]
channels = ["conda-forge"]
description = "A comparison of machine learning model performance on non-avian audio"
name = "non-avian-ml-toy"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10"
libgl = "*"
glib = "*"
ipykernel = ">=6.29.5,<7"

[pypi-dependencies] 
opensoundscape = ">=0.11.0"
tensorflow_hub = "*"
torch = "*"
numpy = "*"
pandas = "*"
tqdm = "*"
timm = "*"
torchaudio = "*"
tensorflow = "*"
scikit-learn = "*"
