name: Base Image

on:
  workflow_dispatch: null
  push:
    paths: ['.devcontainer/*']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      # Free up disk space for large images
      - name: Cleanup disk space
        run: sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc

      - uses: actions/checkout@v3

      # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Configure Docker for Artifact Registry
      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      # Build Docker image with both tags
      - name: Build Docker image
        run: |
          IMAGE=us-central1-docker.pkg.dev/dse-staff/non-avian-ml/model
          docker build base \
            --tag $IMAGE:latest \
            --tag $IMAGE:${{ github.sha }}

      # Push both tags
      - name: Push Docker image
        run: |
          IMAGE=us-central1-docker.pkg.dev/dse-staff/non-avian-ml/model
          docker push $IMAGE:latest
          docker push $IMAGE:${{ github.sha }}